name: Ppv & dlive M3U8 to M3U

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC (optional)

jobs:
  convert-m3u8-to-m3u:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js (if needed for processing)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl wget
        
    - name: Download M3U8 files
      run: |
        # Your M3U8 file URLs
        PPV_URL="https://raw.githubusercontent.com/pigzillaaa/iptv-scraper/refs/heads/main/ppv.m3u8"
        DLIVE_CHANNELS_URL="https://raw.githubusercontent.com/pigzillaaa/daddylive/refs/heads/main/daddylive-channels.m3u8"
        DLIVE_EVENTS_URL="https://raw.githubusercontent.com/pigzillaaa/daddylive/refs/heads/main/daddylive-events.m3u8"
        
        # Create output directory
        mkdir -p downloads
        
        # Download PPV M3U8 file
        echo "Downloading PPV M3U8 file..."
        wget -O downloads/ppv.m3u8 "$PPV_URL" || curl -o downloads/ppv.m3u8 "$PPV_URL"
        
        # Download DaddyLive M3U8 files
        echo "Downloading DaddyLive Channels M3U8 file..."
        wget -O downloads/daddylive-channels.m3u8 "$DLIVE_CHANNELS_URL" || curl -o downloads/daddylive-channels.m3u8 "$DLIVE_CHANNELS_URL"
        
        echo "Downloading DaddyLive Events M3U8 file..."
        wget -O downloads/daddylive-events.m3u8 "$DLIVE_EVENTS_URL" || curl -o downloads/daddylive-events.m3u8 "$DLIVE_EVENTS_URL"
        
    - name: Convert M3U8 to M3U
      run: |
        # Create conversion script
        cat > convert_to_m3u.py << 'EOF'
        import os
        import re
        
        def convert_m3u8_to_m3u(input_file, output_file):
            """Convert M3U8 format to M3U format"""
            try:
                with open(input_file, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                # Remove M3U8 specific tags but keep essential ones
                lines = content.split('\n')
                m3u_lines = []
                
                for line in lines:
                    line = line.strip()
                    if not line:
                        continue
                    
                    # Keep M3U header
                    if line.startswith('#EXTM3U'):
                        m3u_lines.append(line)
                    # Keep track info
                    elif line.startswith('#EXTINF:'):
                        m3u_lines.append(line)
                    # Keep URLs (not starting with #)
                    elif not line.startswith('#'):
                        m3u_lines.append(line)
                    # Optionally keep some other tags
                    elif line.startswith('#EXTVLCOPT:'):
                        m3u_lines.append(line)
                
                # Write M3U file
                with open(output_file, 'w', encoding='utf-8') as f:
                    f.write('\n'.join(m3u_lines))
                
                print(f"Successfully converted {input_file} to {output_file}")
                return True
                
            except Exception as e:
                print(f"Error converting {input_file}: {str(e)}")
                return False
        
        def combine_m3u8_files(file1, file2, output_file):
            """Combine two M3U8 files into one M3U format file"""
            try:
                combined_content = []
                files_processed = []
                
                # Process each file
                for input_file in [file1, file2]:
                    if os.path.exists(input_file):
                        with open(input_file, 'r', encoding='utf-8') as f:
                            content = f.read()
                        
                        lines = content.split('\n')
                        for line in lines:
                            line = line.strip()
                            if not line:
                                continue
                            
                            # Add M3U header only once
                            if line.startswith('#EXTM3U'):
                                if not combined_content:
                                    combined_content.append(line)
                            # Keep track info
                            elif line.startswith('#EXTINF:'):
                                combined_content.append(line)
                            # Keep URLs (not starting with #)
                            elif not line.startswith('#'):
                                combined_content.append(line)
                            # Keep some other tags
                            elif line.startswith('#EXTVLCOPT:'):
                                combined_content.append(line)
                        
                        files_processed.append(input_file)
                        print(f"Processed {input_file}")
                
                # Ensure we have M3U header
                if not any(line.startswith('#EXTM3U') for line in combined_content):
                    combined_content.insert(0, '#EXTM3U')
                
                # Write combined M3U file
                with open(output_file, 'w', encoding='utf-8') as f:
                    f.write('\n'.join(combined_content))
                
                print(f"Successfully combined {files_processed} into {output_file}")
                return True
                
            except Exception as e:
                print(f"Error combining files: {str(e)}")
                return False
        
        # Convert files directly to root directory
        # Convert PPV file
        if os.path.exists('downloads/ppv.m3u8'):
            convert_m3u8_to_m3u('downloads/ppv.m3u8', 'ppv.m3u')
        
        # Combine DaddyLive channels and events into one M3U file
        combine_m3u8_files('downloads/daddylive-channels.m3u8', 'downloads/daddylive-events.m3u8', 'dlive.m3u')
        EOF
        
        # Run the conversion
        python3 convert_to_m3u.py
        
    - name: Display results
      run: |
        echo "=== Conversion Results ==="
        if [ -f "ppv.m3u" ]; then
          echo "✓ ppv.m3u created successfully"
          echo "Size: $(ls -lh ppv.m3u | awk '{print $5}')"
        fi
        
        if [ -f "dlive.m3u" ]; then
          echo "✓ dlive.m3u created successfully"
          echo "Size: $(ls -lh dlive.m3u | awk '{print $5}')"
        fi
        
        echo ""
        echo "=== Root Directory Contents ==="
        ls -la *.m3u
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: converted-m3u-files
        path: |
          ppv.m3u
          dlive.m3u
          downloads/*.m3u8
        retention-days: 7

    - name: Commit and push results (optional)
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if [ -n "$(git status --porcelain)" ]; then
          git add ppv.m3u dlive.m3u
          git commit -m "Auto-update: Convert M3U8 to M3U files $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes to commit"
        fi
